<?php
/**
 * LabelPrepPreference
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound;
use \ClouSale\AmazonSellingPartnerAPI\ObjectSerializer;
use \ClouSale\AmazonSellingPartnerAPI\Models\ModelInterface;

/**
 * LabelPrepPreference Class Doc Comment
 *
 * @category Class
 * @description The preference for label preparation for an inbound shipment.
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LabelPrepPreference
{
    /**
     * Possible values of this enum
     */
    const SELLER_LABEL = 'SELLER_LABEL';
const AMAZON_LABEL_ONLY = 'AMAZON_LABEL_ONLY';
const AMAZON_LABEL_PREFERRED = 'AMAZON_LABEL_PREFERRED';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SELLER_LABEL,
self::AMAZON_LABEL_ONLY,
self::AMAZON_LABEL_PREFERRED,        ];
    }
}
