<?php
/**
 * PrepGuidance
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound;
use \ClouSale\AmazonSellingPartnerAPI\ObjectSerializer;
use \ClouSale\AmazonSellingPartnerAPI\Models\ModelInterface;

/**
 * PrepGuidance Class Doc Comment
 *
 * @category Class
 * @description Item preparation instructions.
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PrepGuidance
{
    /**
     * Possible values of this enum
     */
    const CONSULT_HELP_DOCUMENTS = 'ConsultHelpDocuments';
const NO_ADDITIONAL_PREP_REQUIRED = 'NoAdditionalPrepRequired';
const SEE_PREP_INSTRUCTIONS_LIST = 'SeePrepInstructionsList';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONSULT_HELP_DOCUMENTS,
self::NO_ADDITIONAL_PREP_REQUIRED,
self::SEE_PREP_INSTRUCTIONS_LIST,        ];
    }
}
