<?php
/**
 * FulfillmentOrderItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FulfillmentOrderItemTest Class Doc Comment
 *
 * @category    Class
 * @description Item information for a fulfillment order.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FulfillmentOrderItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FulfillmentOrderItem"
     */
    public function testFulfillmentOrderItem()
    {
    }

    /**
     * Test attribute "seller_sku"
     */
    public function testPropertySellerSku()
    {
    }

    /**
     * Test attribute "seller_fulfillment_order_item_id"
     */
    public function testPropertySellerFulfillmentOrderItemId()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "gift_message"
     */
    public function testPropertyGiftMessage()
    {
    }

    /**
     * Test attribute "displayable_comment"
     */
    public function testPropertyDisplayableComment()
    {
    }

    /**
     * Test attribute "fulfillment_network_sku"
     */
    public function testPropertyFulfillmentNetworkSku()
    {
    }

    /**
     * Test attribute "order_item_disposition"
     */
    public function testPropertyOrderItemDisposition()
    {
    }

    /**
     * Test attribute "cancelled_quantity"
     */
    public function testPropertyCancelledQuantity()
    {
    }

    /**
     * Test attribute "unfulfillable_quantity"
     */
    public function testPropertyUnfulfillableQuantity()
    {
    }

    /**
     * Test attribute "estimated_ship_date_time"
     */
    public function testPropertyEstimatedShipDateTime()
    {
    }

    /**
     * Test attribute "estimated_arrival_date_time"
     */
    public function testPropertyEstimatedArrivalDateTime()
    {
    }

    /**
     * Test attribute "per_unit_price"
     */
    public function testPropertyPerUnitPrice()
    {
    }

    /**
     * Test attribute "per_unit_tax"
     */
    public function testPropertyPerUnitTax()
    {
    }

    /**
     * Test attribute "per_unit_declared_value"
     */
    public function testPropertyPerUnitDeclaredValue()
    {
    }
}
