<?php
/**
 * FulfillmentShipmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FulfillmentShipmentTest Class Doc Comment
 *
 * @category    Class
 * @description Delivery and item information for a shipment in a fulfillment order.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FulfillmentShipmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FulfillmentShipment"
     */
    public function testFulfillmentShipment()
    {
    }

    /**
     * Test attribute "amazon_shipment_id"
     */
    public function testPropertyAmazonShipmentId()
    {
    }

    /**
     * Test attribute "fulfillment_center_id"
     */
    public function testPropertyFulfillmentCenterId()
    {
    }

    /**
     * Test attribute "fulfillment_shipment_status"
     */
    public function testPropertyFulfillmentShipmentStatus()
    {
    }

    /**
     * Test attribute "shipping_date_time"
     */
    public function testPropertyShippingDateTime()
    {
    }

    /**
     * Test attribute "estimated_arrival_date_time"
     */
    public function testPropertyEstimatedArrivalDateTime()
    {
    }

    /**
     * Test attribute "fulfillment_shipment_item"
     */
    public function testPropertyFulfillmentShipmentItem()
    {
    }

    /**
     * Test attribute "fulfillment_shipment_package"
     */
    public function testPropertyFulfillmentShipmentPackage()
    {
    }
}
