<?php
/**
 * OrderItemBuyerInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderItemBuyerInfoTest Class Doc Comment
 *
 * @category    Class
 * @description A single order item&#x27;s buyer information.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderItemBuyerInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderItemBuyerInfo"
     */
    public function testOrderItemBuyerInfo()
    {
    }

    /**
     * Test attribute "order_item_id"
     */
    public function testPropertyOrderItemId()
    {
    }

    /**
     * Test attribute "buyer_customized_info"
     */
    public function testPropertyBuyerCustomizedInfo()
    {
    }

    /**
     * Test attribute "gift_wrap_price"
     */
    public function testPropertyGiftWrapPrice()
    {
    }

    /**
     * Test attribute "gift_wrap_tax"
     */
    public function testPropertyGiftWrapTax()
    {
    }

    /**
     * Test attribute "gift_message_text"
     */
    public function testPropertyGiftMessageText()
    {
    }

    /**
     * Test attribute "gift_wrap_level"
     */
    public function testPropertyGiftWrapLevel()
    {
    }
}
