<?php
/**
 * QualifiersTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QualifiersTypeTest Class Doc Comment
 *
 * @category    Class
 * @description QualifiersType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QualifiersTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QualifiersType"
     */
    public function testQualifiersType()
    {
    }

    /**
     * Test attribute "item_condition"
     */
    public function testPropertyItemCondition()
    {
    }

    /**
     * Test attribute "item_subcondition"
     */
    public function testPropertyItemSubcondition()
    {
    }

    /**
     * Test attribute "fulfillment_channel"
     */
    public function testPropertyFulfillmentChannel()
    {
    }

    /**
     * Test attribute "ships_domestically"
     */
    public function testPropertyShipsDomestically()
    {
    }

    /**
     * Test attribute "shipping_time"
     */
    public function testPropertyShippingTime()
    {
    }

    /**
     * Test attribute "seller_positive_feedback_rating"
     */
    public function testPropertySellerPositiveFeedbackRating()
    {
    }
}
