<?php
/**
 * SellerInputDefinitionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SellerInputDefinitionTest Class Doc Comment
 *
 * @category    Class
 * @description Specifies characteristics that apply to a seller input.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SellerInputDefinitionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SellerInputDefinition"
     */
    public function testSellerInputDefinition()
    {
    }

    /**
     * Test attribute "is_required"
     */
    public function testPropertyIsRequired()
    {
    }

    /**
     * Test attribute "data_type"
     */
    public function testPropertyDataType()
    {
    }

    /**
     * Test attribute "constraints"
     */
    public function testPropertyConstraints()
    {
    }

    /**
     * Test attribute "input_display_text"
     */
    public function testPropertyInputDisplayText()
    {
    }

    /**
     * Test attribute "input_target"
     */
    public function testPropertyInputTarget()
    {
    }

    /**
     * Test attribute "stored_value"
     */
    public function testPropertyStoredValue()
    {
    }

    /**
     * Test attribute "restricted_set_values"
     */
    public function testPropertyRestrictedSetValues()
    {
    }
}
