<?php
/**
 * ShippingServiceOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ShippingServiceOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Extra services provided by a carrier.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingServiceOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingServiceOptions"
     */
    public function testShippingServiceOptions()
    {
    }

    /**
     * Test attribute "delivery_experience"
     */
    public function testPropertyDeliveryExperience()
    {
    }

    /**
     * Test attribute "declared_value"
     */
    public function testPropertyDeclaredValue()
    {
    }

    /**
     * Test attribute "carrier_will_pick_up"
     */
    public function testPropertyCarrierWillPickUp()
    {
    }

    /**
     * Test attribute "carrier_will_pick_up_option"
     */
    public function testPropertyCarrierWillPickUpOption()
    {
    }

    /**
     * Test attribute "label_format"
     */
    public function testPropertyLabelFormat()
    {
    }
}
